spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  
  datasource:
    url: ${DATASOURCE_URL}
  #    username: ${DATASOURCE_USERNAME}
  #    password: ${DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

patreon:
  client-id: ${PATREON_CLIENT_ID}
  client-secret: ${PATREON_CLIENT_SECRET}
  redirect-uri: ${PATREON_CLIENT_REDIRECT_URI}

telegram:
  token: ${TELEGRAM_TOKEN}